# Generated by Django 5.1.4 on 2025-01-27 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket', models.CharField(max_length=20, unique=True)),
                ('start_park', models.DateTimeField(auto_now_add=True)),
                ('end_park', models.DateTimeField(blank=True, null=True)),
                ('total_price', models.IntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parkings', to='category.categorymodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parkings', to='profiles.userprofile')),
            ],
        ),
    ]
