# Generated by Django 5.1.4 on 2025-01-27 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Parking', '0003_alter_parkingmodels_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingmodels',
            name='end_park',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
