# Generated by Django 5.1.4 on 2025-01-28 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Parking', '0004_alter_parkingmodels_end_park'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingmodels',
            name='car_name',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
