# Generated by Django 5.1.4 on 2025-01-28 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Parking', '0005_parkingmodels_car_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingmodels',
            name='is_complete',
            field=models.BooleanField(default=False),
        ),
    ]
