# Generated by Django 5.1.4 on 2025-02-01 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Parking', '0006_parkingmodels_is_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingmodels',
            name='slot',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
