# Generated by Django 5.1.4 on 2025-02-01 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Parking', '0010_alter_parkingmodels_slot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingmodels',
            name='slot',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
