# Generated by Django 5.1.4 on 2025-02-04 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Parking', '0011_alter_parkingmodels_slot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingmodels',
            name='start_park',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
